# .github/workflows/ci.yml
name: CI (Quality Gates)

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: app/package-lock.json
      - name: Install deps
        working-directory: app
        run: npm ci
      - name: Run ESLint
        working-directory: app
        run: npm run lint

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: app/package-lock.json
      - name: Install deps
        working-directory: app
        run: npm ci
      - name: Prettier check
        working-directory: app
        run: npm run format -- -c # prettier --check .

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: app/package-lock.json
      - name: Install deps
        working-directory: app
        run: npm ci
      - name: Run tests
        working-directory: app
        run: npm run test -- --coverage

  build:
    runs-on: ubuntu-latest
    needs: [lint, format, test]
    env:
      DOCKER_BUILDKIT: "1"
      IMAGE: devops-apprentice-app
      TAG: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v5
      - name: Build image
        run: docker build -t $IMAGE:$TAG ./app
