name: Terraform CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  terraform_checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.6  # Use a specific Terraform version

      - name: Set up TFLint
        uses: terraform-linters/setup-tflint@v5

      - name: Terraform Format (validation)
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Lint
        run: tflint
